# Site settings
title: "Gerald A. Wakefield"
email: gwake1@gmail.com	
description: "The journey of a future full-stack developer"  
baseurl: "/about/"
url: "gwake1.github.io/about/" # the base hostname & protocol for your site
twitter_username: gwake1
github_username:  gwake1

# Build settings
markdown: kramdown
