# Site settings
title: Gerald's Blog
email: gwake1@gmail.com	
description: "The journey of a future full-stack developer"  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "gwake1.github.io" # the base hostname & protocol for your site
twitter_username: gwake1
github_username:  gwake1

# Build settings
markdown: kramdown
