# Site settings
title: Gerald's Portfolio
email: gwake1@gmail.com
url: http://geraldwakefield.io
description: "I am a poassionate junior software developer producing applications to communicate detailed information in meaningful ways."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Gerald A. Wakefield

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/gwake1
  - title: linkedin
    url: https://www.linkedin.com/in/geraldawakefield
  - title: twitter
    url: https://twitter.com/gwake1

# Build settings
markdown: kramdown
permalink: pretty
