# JEKYLL
exclude: [".gitignore", ".git", "config.rb", "package.json", "Gruntfile.js", "bower_components", ".travis.yml", "ai", "src", "VERSION", "LICENSE", "README.md", "icon.png", "node_modules"]

# Site settings
title: "Gerald A. Wakefield"
email: "gwake1@gmail.com"
phone: "(615) 988-1669"
description: "The personal website of Gerald A. Wakefield documenting success and failure to become a software developer."
baseurl: ""
url: "gwake1.github.io"
environment: production
twitter_username: gwake1
github_username:  gwake1
safe: true
timezone: America/Chicago

permalink: /:year/:month/:title/
paginate: 5
paginate_path: "blog/page:num/"

# INK LATEST VERSION
version: 3.1.4

# URLS
cdn_url: http://fastly.ink.sapo.pt/

sections:
  - title: Blog
  - title: Portfolio
    components:
      - title: Grid
        topics:
          - title: Basic principles

releases:
  - 3.0.0
  - 2.3.2
  - 2.3.1
  - 2.3.0
  - 2.2.1
  - 2.2.0
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.1.0
  - 0.1.0

# Build settings
markdown: kramdown
permalink: pretty
