# Site settings
title: "Gerald A. Wakefield"
email: "gwake1@gmail.com"
phone: "(615) 988-1669"
description: "The journey of a future full-stack developer"
baseurl: ""
url: "gwake1.github.io" # the base hostname & protocol for your site
twitter_username: gwake1
github_username:  gwake1

# Build settings
markdown: kramdown
